"""announcements table

Revision ID: 1861adbac23a
Revises: bc51611008ce
Create Date: 2026-07-07 18:41:03.084928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1861adbac23a'
down_revision = 'bc51611008ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_is_published'), ['is_published'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_is_published'))
        batch_op.drop_index(batch_op.f('ix_announcements_created_at'))
        batch_op.drop_index(batch_op.f('ix_announcements_category'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
