"""user lockout fields

Revision ID: 52220c96b20d
Revises: f492474fa0d4
Create Date: 2026-08-10 17:21:39.634250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52220c96b20d'
down_revision = 'f492474fa0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_count')

    # ### end Alembic commands ###
