"""foundation schema

Revision ID: 81da5a8c9e64
Revises: 
Create Date: 2026-07-07 18:03:52.171788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81da5a8c9e64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_name'), ['name'], unique=True)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_staff_name'), ['name'], unique=False)

    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_staff_id'), ['staff_id'], unique=False)

    op.create_table('recognition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('award_type', sa.String(length=120), nullable=False),
    sa.Column('granted_by', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recognition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recognition_staff_id'), ['staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recognition_staff_id'))

    op.drop_table('recognition')
    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_staff_id'))

    op.drop_table('performance')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_name'))
        batch_op.drop_index(batch_op.f('ix_staff_employee_id'))
        batch_op.drop_index(batch_op.f('ix_staff_department_id'))

    op.drop_table('staff')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_name'))

    op.drop_table('departments')
    # ### end Alembic commands ###
