"""recognition note

Revision ID: bc51611008ce
Revises: b2ef9ecb9daa
Create Date: 2026-07-07 18:36:42.640918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc51611008ce'
down_revision = 'b2ef9ecb9daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recognition', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
